/**
 * Deploy OpenHood marketplace + test NFT to Robinhood testnet (or hardhat).
 *
 * Usage:
 *   # local dry-run
 *   npx hardhat run scripts/deploy.cjs
 *
 *   # Robinhood testnet
 *   set DEPLOYER_PRIVATE_KEY=0x...
 *   npx hardhat run scripts/deploy.cjs --network robinhoodTestnet
 */
const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  if (!deployer) {
    throw new Error(
      "No deployer account. Set DEPLOYER_PRIVATE_KEY env var (with testnet ETH)."
    );
  }

  const network = hre.network.name;
  const chainId = (await hre.ethers.provider.getNetwork()).chainId;
  const balance = await hre.ethers.provider.getBalance(deployer.address);

  console.log("=== OpenHood deploy ===");
  console.log("Network:", network, "chainId:", chainId.toString());
  console.log("Deployer:", deployer.address);
  console.log("Balance:", hre.ethers.formatEther(balance), "ETH");

  if (balance === 0n) {
    throw new Error(
      "Deployer has 0 ETH. Fund on Robinhood testnet faucet before deploying."
    );
  }

  // 2.5% protocol fee → deployer as fee recipient (change later via setFee)
  const feeBps = 250;
  const feeRecipient = process.env.FEE_RECIPIENT || deployer.address;

  console.log("\n1) Deploying MockERC721...");
  const NFT = await hre.ethers.getContractFactory("MockERC721");
  const nft = await NFT.deploy(
    "OpenHood Demo NFT",
    "OHD",
    "https://openhood.app/api/nft/"
  );
  await nft.waitForDeployment();
  const nftAddr = await nft.getAddress();
  console.log("   MockERC721:", nftAddr);

  console.log("\n2) Deploying OpenHoodMarketplace...");
  const Market = await hre.ethers.getContractFactory("OpenHoodMarketplace");
  const market = await Market.deploy(feeRecipient, feeBps);
  await market.waitForDeployment();
  const marketAddr = await market.getAddress();
  console.log("   Marketplace:", marketAddr);
  console.log("   Fee:", feeBps / 100, "% →", feeRecipient);

  // Mint a few test NFTs to deployer for manual testing
  console.log("\n3) Minting 5 test NFTs to deployer...");
  const tx = await nft.mintBatch(deployer.address, 5);
  await tx.wait();
  console.log("   Token IDs 1–5 minted to", deployer.address);

  const out = {
    network,
    chainId: Number(chainId),
    deployedAt: new Date().toISOString(),
    deployer: deployer.address,
    feeBps,
    feeRecipient,
    contracts: {
      OpenHoodMarketplace: marketAddr,
      MockERC721: nftAddr,
    },
    explorer: {
      marketplace:
        chainId === 46630n
          ? `https://explorer.testnet.chain.robinhood.com/address/${marketAddr}`
          : null,
      nft:
        chainId === 46630n
          ? `https://explorer.testnet.chain.robinhood.com/address/${nftAddr}`
          : null,
    },
  };

  const outDir = path.join(__dirname, "..", "deployments");
  fs.mkdirSync(outDir, { recursive: true });
  const file = path.join(outDir, `${network}.json`);
  fs.writeFileSync(file, JSON.stringify(out, null, 2));
  console.log("\nWrote", file);
  console.log(JSON.stringify(out, null, 2));

  // Frontend-friendly env snippet
  const envSnippet = `
# Auto-generated by scripts/deploy.cjs (${network})
VITE_MARKETPLACE_ADDRESS=${marketAddr}
VITE_DEMO_NFT_ADDRESS=${nftAddr}
VITE_CHAIN_ID=${Number(chainId)}
`.trim();
  fs.writeFileSync(path.join(outDir, `${network}.env`), envSnippet + "\n");
  console.log("\nEnv snippet written to deployments/" + network + ".env");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
